uint16 END_OF_SCAN_ID = 65535

float32 x
float32 y
float32 z
float32 intensity
uint16 id

# module autoware_auto_msgs {
#   module msg {
#     module PointXYZIF_Constants {
#       const uint16 END_OF_SCAN_ID = 65535;
#     };
#     @verbatim (language="comment", text=
#       " This message is meant to mirror autoware::common::types::PointXYZIF")
#     struct PointXYZIF {
#       float x;

#       float y;

#       float z;

#       float intensity;

#       uint16 id;
#     };
#   };
# };

